OpenAgentsInc/openagents

app/AI/Models.php
One of the smallest PRs in history, but if we have to have those comments they should be in correct place.
=> fix: move OPENAI models comment to correct place

app/AI/AnthropicAIGateway.php, app/AI/CohereAIGateway.php, app/AI/OpenAIGateway.php, app/AI/PerplexityAIGateway.php, app/Livewire/Auth/Register.php
Some of the gateways had a private client setup, but are not using it. Another one is using it but it was not declared. This is an initial cleanup, but might be a good idea to make them all consistent for easier maintenance in the future?
=> fix: php cleanup

app/AI/AnthropicAIGateway.php, app/AI/CohereAIGateway.php, app/AI/GatewayInterface.php, app/AI/HuggingfaceAIGateway.php, app/AI/MistralAIGateway.php, app/AI/OpenAIGateway.php, app/AI/PerplexityAIGateway.php, app/AI/SimpleInferencer.php, tests/Pest.php, tests/Unit/AnthropicAIGatewayTest.php, tests/Unit/CohereAIGatewayTest.php, tests/Unit/HugginfaceAIGatewayTest.php, tests/Unit/MistralAIGatewayTest.php, tests/Unit/OpenAIGatewayTest.php, tests/Unit/PerplexityAIGatewayTest.php
- created initial `Gateway` interface with a single `inference` method
- converted all active gateways to implement new interface
- added http client class variable to most gateways to be able to mock api calls
- add unit tests for all converted gateways
- removed some unused code
- made all added/updated use strict mode
=> refactor: add Gateway interface, use it in active gateways

.github/workflows/laravel.yml
Posting comments from PRs coming from forks is proving too complicated. Use regular action error messages instead.
=> fix: avoid false negatives in PR test runs

app/Console/Commands/UpdatePrismStatuses.php, tests/Feature/UpdatePrimsStatusesTest.php
Also add a test, mostly mocked for now, but hitting the current error case of no status available.
=> fix: do not update payments when no status received

resources/views/components/chat/message.blade.php, resources/views/components/chat/textarea.blade.php, resources/views/livewire/chat.blade.php
Allow using ALT+up/down arrow keys to scroll through prompt history in the current thread.
TODO: handle code and other special formatting smarter, currently simply copies the text content of the prompt.
=> feat: ability to edit my last prompt and resubmit it

app/AI/GreptileGateway.php, app/AI/SimpleInferencer.php, app/AI/TogetherAIGateway.php, app/Livewire/Chat.php
For now just avoid warnings and errors if empty content somehow sneaks in (usually due to some failure on LLM side.)
=> fix: avoid errors due to null content

resources/views/components/chat/textarea.blade.php
If a user starts typing and then uses up/down keys, remember the current prompt to be able to come to it and not lose what was typed so far.
=> feat: remember current prompt before moving up or down

app/Livewire/Chat.php, resources/views/components/chat/messagestreaming.blade.php, resources/views/livewire/chat.blade.php
When a stream starts in one thread and a new thread is started, use a different stream name to avoid streams overwriting each other.
=> fix: use unique stream names to avoid conflicts

app/AI/OpenAIGateway.php
Our estimation of token counts can be improved, but will never be exact, and sometimes are off by a lot. We can still truncate messages on our end to optimize network traffic and other costs, but let the api decide.
=> fix: no need to give max-tokens to OpenAI, it handles it well

app/AI/CohereAIGateway.php, app/AI/NostrInference.php, app/AI/SimpleInferencer.php, app/Livewire/Chat.php
* add systemPrompt argument to inference call so that rag and non-rag agents can override it as needed
* if Cohere gets an empty prompt (because of rag context) use the last message from the thread
=> better way to fix the rag prompt

configuration/base.yaml, configuration/production.yaml, src/configuration.rs, src/db.rs, src/main.rs
This PR adds connection resilience to the database initialization process to handle cases where the database might be temporarily unavailable or still provisioning. Changes include:
1. Added connection timeout and retry settings to database configuration:
- `connection_timeout_secs`: How long to wait for each connection attempt
- `max_connection_retries`: Number of times to retry connecting
- `retry_interval_secs`: Time to wait between retries
2. Enhanced Database initialization with retry logic:
- Will attempt to connect multiple times before giving up
- Logs each failed attempt with details
- Configurable retry parameters through YAML config or environment variables
3. Updated configuration files:
- Base config: 30s timeout, 5 retries, 5s interval
- Production config: 60s timeout, 10 …
=> Add database connection resilience

src/configuration.rs, src/main.rs, src/server/admin/middleware.rs, src/server/admin/mod.rs, src/server/admin/routes.rs, src/server/config.rs, src/server/mod.rs, src/server/routes.rs
Fixes #522
Implements admin panel infrastructure and fixes static file serving:
- Adds basic authentication middleware with token-based auth
- Adds protected `/admin` routes with middleware
- Implements initial `/admin/stats` endpoint
- Fixes static file serving by using correct `./static` path
- Includes tests for admin authentication
The admin panel is protected by token authentication via the `APP_APPLICATION__ADMIN_TOKEN` environment variable.
Tested:
- Server serves index.html correctly from http://127.0.0.1:8080
- Static files are properly served from the local static directory
- Admin authentication works with token
- Admin routes are properly protected
=> Add admin panel infrastructure and fix static file serving

static/agents.html, static/index.html, static/templates/button.mustache, static/templates/textinput.mustache, static/video-series.html
Standardize HTMX/Mustache front end components, add Tailwind, and maximize reusability.
* **Button Component**
- Add Tailwind CSS classes to the button template in `static/templates/button.mustache`.
* **Agents Page**
- Replace inline styles with Tailwind CSS classes in `static/agents.html`.
- Update the agent creation form to use the new textinput Mustache component.
* **Index Page**
- Replace inline styles with Tailwind CSS classes in `static/index.html`.
* **Video Series Page**
- Replace inline styles with Tailwind CSS classes in `static/video-series.html`.
* **Textinput Component**
- Create a new Mustache component for textinput with Tailwind CSS classes in `static/templates/textinput.mustache`.
---
For more details, open the [Copilot Workspace …
=> Standardize HTMX/Mustache front end components with Tailwind CSS

src/server/routes.rs, static/business.html, static/company.html, static/contact.html, static/mobile-app.html, static/templates/button.mustache, static/templates/header.mustache, static/video-series.html
Add pages for the six buttons at the top using a shared layout, with a white border and no radius, and use hx-boost to prevent the top from reloading.
* **Shared Layout**: Add `hx-boost` attribute and white border with no radius to the `<a>` tag in `static/templates/button.mustache`.
* **Header Template**: Update `static/templates/header.mustache` to use the shared layout `static/templates/button.mustache`.
* **New Pages**: Create new HTML files for Mobile App (`static/mobile-app.html`), Business Services (`static/business.html`), Company (`static/company.html`), and Contact (`static/contact.html`) using the shared layout.
* **Video Series Page**: Update `static/video-series.html` to use the shared layout.
* **Routes**: Add routes for the new pages in `src/server/routes.rs`.
---
For more …
=> Add pages for buttons with shared layout and hx-boost

static/index.html, static/templates/header.mustache
This PR optimizes the header navigation to prevent re-rendering when navigating between pages. Changes include:
1. Added hx-preserve to the header component
2. Moved header template to a separate file for better organization
3. Added proper HTMX boost and client-side template configuration
4. Added event listener to prevent header re-rendering during page swaps
5. Removed duplicate client-side-templates.js script include
The changes ensure that:
- Header state is preserved during navigation
- Navigation is smooth and efficient
- Templates are properly organized and maintainable
- No unnecessary re-renders occur
Testing:
1. Header should load correctly on initial page load
2. Navigation between pages should be smooth
3. Header should not re-render when clicking navigation links
4. All …
=> Optimize header navigation with hx-preserve and client-side templates

templates/macros/blog.html
Updated the blog macro to match the video macro's date formatting style:
- Changed date from right-aligned to inline with title
- Updated HTML structure to match video macro
- Replaced span with p tag for consistency
- Added gap-4 spacing between title and date
=> Update blog macro date formatting

.github/workflows/general.yml, Cargo.lock, Cargo.toml, Dockerfile, src/lib.rs, src/main.rs
This PR addresses three dependency-related issues:
1. Replaces unmaintained `dotenv` with `dotenvy` (RUSTSEC-2021-0141)
2. Upgrades `sqlx` to version 0.8.1 to fix security vulnerability (RUSTSEC-2024-0363)
3. Upgrades `config` to version 0.14 to address unmaintained `yaml-rust` dependency (RUSTSEC-2024-0320)
Changes:
- Replace `dotenv = "0.15"` with `dotenvy = "0.15"`
- Upgrade `sqlx` from 0.7.4 to 0.8.1
- Upgrade `config` from 0.13 to 0.14
Note: Code changes may be needed to update from `dotenv` to `dotenvy`. The main difference is in the import statement:
```rust
// Old
use dotenv::dotenv;
// New
use dotenvy::dotenv;
```
=> Fix security and maintenance issues in dependencies

src/main.rs
This PR adds a health check endpoint to fix the Digital Ocean health check failures.
Changes:
- Added `/health` endpoint that returns `{"status": "healthy"}`
- Endpoint matches the test in tests/health_check.rs
- Uses axum's Json response type for proper content-type headers
The health check endpoint will now respond with a 200 status code and the expected JSON response, which should satisfy Digital Ocean's health check requirements.
=> Add health check endpoint

src/server/admin/routes.rs, src/server/mod.rs, src/server/services/solver/ws/transport.rs
This PR fixes the WebSocket module imports after the module reorganization:
1. Updated imports in src/server/admin/routes.rs to use the new path:
```rust
use crate::server::services::solver::ws::{ws_handler, SolverWsState};
```
2. Updated imports in src/server/mod.rs to use the new path:
```rust
use services::solver::ws::{ws_handler, SolverWsState};
```
3. Removed unused SolverStage import in src/server/services/solver/ws/transport.rs
These changes fix the compilation errors:
```
error[E0432]: unresolved import `crate::server::services::solver_ws`
error[E0432]: unresolved import `services::solver_ws`
warning: unused import: `SolverStage`
```
=> Fix WebSocket module imports

Cargo.toml
Fixes #584
The mockall dependency was in [dev-dependencies] but is being used in the main code. This PR moves it to the main dependencies section.
Changes:
- Moved mockall dependency from [dev-dependencies] to [dependencies]
- Kept the same version and features (0.12.0 with async feature)
This should resolve the dependency resolution error:
```
error: failed to select a version for `mockall`.
... required by package `openagents v0.1.0 (/Users/christopherdavid/code/openagents)`
versions that meet the requirements `^0.12.0` (locked to 0.12.1) are: 0.12.1
the package `openagents` depends on `mockall`, with features: `async` but `mockall` does not have these features.
```
=> Fix mockall dependency issue

src/bin/deepseek-cli.rs
This PR fixes the function calling implementation to properly handle the message sequence according to the DeepSeek API requirements.
Changes:
1. Properly sequence messages in the chat_with_tool_response call
2. Remove duplicate weather_message from messages vector
3. Pass weather_message separately as tool response
The error "Messages with role 'tool' must be a response to a preceding message with 'tool_calls'" was occurring because we weren't properly maintaining the required message sequence. This fix ensures that:
1. User message is added first
2. Assistant message with tool_calls is added second
3. Tool response is passed separately with matching tool_call_id
This matches the sequence shown in the DeepSeek function calling documentation.
=> Fix function calling message sequence

src/server/ws/handlers/chat.rs, src/server/ws/mod.rs, src/server/ws/transport.rs
This PR adds the GitHub issue tool to all DeepSeek chat messages by:
1. Modifying the ChatHandler to use chat_with_tools instead of chat_stream
2. Adding GitHub service to WebSocketState and passing it through to ChatHandler
3. Updating the handle_socket function to initialize the GitHub service
This allows DeepSeek to access GitHub issues in any chat conversation, not just through the CLI tool.
=> Add GitHub issue tool to all DeepSeek chat messages

tailwind.config.cjs
Updates the Tailwind typography configuration to use text-xs (0.75rem) as the base size for prose content, with proportionally adjusted heading sizes. This change maintains the existing font configuration while making all prose text smaller.
Changes:
- Set base prose font size to 0.75rem (text-xs)
- Adjusted heading sizes proportionally
- Applied text-xs to paragraphs and list items
- Preserved existing font family and other configurations
=> Update prose text size to xs

assets/main.css, templates/components/chat/login_overlay.html, templates/components/chat/websocket_scripts.html, templates/layouts/chat_base.html
This PR replaces the bottom-right connection error message with a centered login overlay when users are not authenticated.
Changes:
1. Added new login_overlay.html component with a centered design
2. Updated chat_base.html to include the login overlay component
3. Modified websocket_scripts.html to:
- Show login overlay instead of error message for auth errors
- Hide login overlay when successfully connected
- Handle both WebSocket errors and message-based auth errors
The login overlay appears when:
- WebSocket connection fails due to auth
- Server sends an auth error message
- Connection attempt returns unauthorized
The overlay is hidden when:
- WebSocket successfully connects (authenticated)
This provides a better UX by clearly indicating when login is required instead of showing a …
=> Add centered login overlay for unauthenticated users

assets/main.css, docs/repomap.md, templates/components/chat/login_overlay.html, templates/components/chat/websocket_scripts.html, templates/layouts/chat_base.html
This PR adds authentication requirements to the chat interface and implements a "Coming Soon" overlay for unauthenticated users.
Changes:
1. Added WebSocket authentication check
2. Added a clean, centered "Coming Soon" overlay that appears when:
- WebSocket connection fails
- User is not authenticated
3. Overlay shows "Under construction, check back soon" message
4. Improved error handling for WebSocket connections
The overlay has a semi-transparent black background with white text and border, providing a clean user experience while the feature is under development.
=> Add authentication requirement with Coming Soon overlay

src/server/handlers/auth.rs
This PR fixes the issue with auth tests failing due to multiple attempts to initialize the global tracing subscriber.
Changes:
- Modified `setup_logging()` to use `std::sync::Once` to ensure the tracing subscriber is only initialized once
- Removed async from `setup_logging()` since it's no longer needed
- Fixed the error: `failed to set global default subscriber: SetGlobalDefaultError("a global default trace dispatcher has already been set")`
The tests should now pass without the logging initialization errors.
=> Fix auth tests logging initialization

tests/oidc_client.rs, tests/oidc_signup.rs
This PR consolidates the test database setup function by:
1. Removing duplicate implementations of `setup_test_db()` from oidc_signup.rs and oidc_client.rs
2. Using the common implementation from tests/common/mod.rs in both test files
This change:
- Removes the "function is never used" warning
- Ensures consistent database setup across tests
- Follows DRY principles by using a single implementation
- Makes test maintenance easier since database setup logic is in one place
Changes:
- Added `use crate::common::setup_test_db;` to both test files
- Removed local `setup_test_db()` implementations
- Now using the common implementation from tests/common/mod.rs
=> Consolidate test database setup function

src/solver/github.rs, src/solver/planning.rs, src/solver/solution.rs
This PR fixes the runtime conflicts in the solver tests by properly handling async code in test functions. The main changes are:
1. In `src/solver/planning.rs`:
- Changed `test_validate_llm_response` to use `Runtime::new()` and `block_on`
- Properly handles async code in a synchronous test context
2. In `src/solver/github.rs`:
- Changed `test_generate_pr_title` to use `Runtime::new()` and `block_on`
- Maintains existing test functionality while fixing runtime issues
3. In `src/solver/solution.rs`:
- Changed `test_handle_solution` to use `Runtime::new()` and `block_on`
- Properly handles async code in test context
The changes ensure that we don't try to start a runtime from within another runtime, which was causing the test failures. Each test now properly creates its own runtime instance …
=> fix: resolve runtime conflicts in solver tests

docs/solve-runs/20250202-1640.md, docs/solver.md, src/bin/solver.rs, src/bin/solver_impl/files.rs, src/bin/solver_impl/mod.rs, src/bin/solver_impl/pre_analysis.rs
This PR adds a DeepSeek pre-analysis step to the solver to improve reasoning capabilities while maintaining structured output format.
Key changes:
1. Added DeepSeek streaming analysis before Mistral's structured output
2. Increased max files from 3 to 10
3. Changed relevance scores from 0-1 to 1-10 (10 being most relevant)
4. Shows real-time token streaming of DeepSeek's reasoning process
The new flow:
1. DeepSeek analyzes the issue and thinks through file modifications, streaming its reasoning in real-time
2. Both the reasoning trace and final analysis are passed to Mistral
3. Mistral formats the output as structured JSON with up to 10 files and 1-10 relevance scores
4. The solver continues with the validated file list
This gives us better reasoning capabilities from DeepSeek while …
=> Add DeepSeek pre-analysis step to solver

docs/repomap.md, templates/pages/login.html
This PR fixes an issue where the login form was submitting to `/login` instead of `/auth/login`, causing a 405 Method Not Allowed error.
Changes:
- Added explicit `action="/auth/login"` attribute to the login form
- Form now correctly submits to the endpoint with POST handler
- Maintains existing JavaScript fetch handler which was already using correct URL
This fixes issue #616 where the login form was getting a 405 error due to submitting to the wrong endpoint.
=> Fix login form submission URL

src/server/handlers/auth/github.rs, src/server/handlers/auth/login.rs, src/server/handlers/auth/mod.rs, src/server/handlers/auth/session.rs, src/server/handlers/auth/signup.rs
This PR adds support for mobile deep linking in the GitHub OAuth callback handler. When the auth flow is initiated from the mobile app, the callback will redirect to `onyx://auth/success?token=SESSION_TOKEN` instead of the web redirect.
Changes:
1. Updated `create_session_and_redirect` to support mobile deep linking
2. Added platform detection in GitHub callback handler
3. Modified GitHub login to preserve platform parameter
Testing:
1. Start auth flow from mobile app with `platform=mobile`
2. Complete GitHub OAuth
3. Verify redirect to `onyx://auth/success` with session token
4. Verify web flow still works without changes
Fixes OpenAgentsInc/onyx#76
=> Add mobile deep linking support for GitHub auth callback

apps/onyx/app/navigators/WalletNavigator.tsx, apps/onyx/app/screens/WalletScreen/AgentEarningsScreen.tsx, apps/onyx/app/screens/WalletScreen/WalletScreen.tsx
This PR adds a new Agent Earnings screen to the Onyx wallet, including:
1. New AgentEarningsScreen component with:
- Total earnings display
- Time period selector (Week/Month/Year/All)
- Earnings breakdown by category
- Progress bars showing relative earnings
- Action buttons for details and withdrawals
2. Updated WalletNavigator to include the new screen
3. Added "Agent Earnings" button to main wallet screen
The earnings categories include:
- MCP Server Usage
- Agent Plugin
- Referral Rewards
- Content Creation
The screen follows the existing wallet's dark theme and design patterns.
Screenshots:
[Add screenshots here when available]
Testing:
- Navigate to Agent Earnings from main wallet screen
- View mock earnings data
- Test time period selector buttons
- Verify back navigation
- Check …
=> Add Agent Earnings screen to Onyx wallet

apps/coder/package.json, apps/coder/src/pages/HomePage.tsx, apps/coder/src/shims/expo-vector-icons.ts, apps/coder/src/shims/load-icon-fonts.ts, apps/coder/src/shims/mock-ionicons.tsx, apps/coder/tsconfig.json, apps/coder/vite.main.config.ts, apps/coder/vite.preload.config.ts, apps/coder/vite.renderer.config.mts, docs/fixes/expo-vector-icons-electron.md, packages/ui/package.json, yarn.lock
This PR implements cross-platform compatibility fixes for @expo/vector-icons in our Electron app, along with comprehensive documentation.
- Added required dependencies to UI package and Electron app
- Created shim for Expo Vector Icons to map to React Native Vector Icons
- Updated Vite configuration for proper React Native and Expo package aliasing
- Fixed TypeScript configuration to include React Native types
- Added detailed documentation explaining the implementation
- Resolves build failures in Electron app
- Enables shared UI components to work consistently across React Native and Electron
- Maintains clean component code through configuration-based platform adaptations
- Provides a pattern for handling similar cross-platform components
The implementation ensures our Toast component …
=> Fix Expo Vector Icons compatibility in Electron

apps/coder/src/App.tsx, apps/coder/src/components/ThreadList.tsx, apps/coder/src/pages/settings/PreferencesPage.tsx, apps/coder/src/pages/settings/SettingsLayout.tsx, apps/coder/src/routes/routes.tsx, apps/coder/src/server/server.ts, docs/fast-delete-threads.md
This PR implements the fast thread deletion feature requested in #825.
- Added new `confirmThreadDeletion` preference to settings
- Implemented conditional confirmation dialog based on user preference
- Added toast notifications with 5-second undo functionality
- Created new preferences page UI for toggling the confirmation setting
- Added documentation in `docs/fast-delete-threads.md`
- Confirm that thread deletion works with confirmation dialog when preference is enabled (default)
- Verify instant deletion works when confirmation is disabled
- Test undo functionality within the 5-second window
- Verify preference persists across page reloads
- Check toast notifications appear correctly with thread title
- Ensure settings UI toggle works as expected
See `docs/fast-delete-threads.md` for …
=> Add fast thread deletion with toggle and undo functionality

.github/workflows/check.yml, .github/workflows/generate-llms-txt.yml, apps/openagents.com/package.json, apps/openagents.com/src/index.ts, apps/openagents.com/static/llms.txt, package.json, pnpm-lock.yaml, scripts/generate-llms-txt.ts, server.log
Implements automated llms.txt generation for improved LLM navigation of OpenAgents documentation.
- ✨ Add llms.txt generator script that parses docs to create spec-compliant file
- 🛣️ Configure route to serve llms.txt at `/llms.txt` endpoint
- 🤖 Add GitHub Actions workflow to auto-generate on docs changes
- 🏗️ Include generation in build process to ensure it stays in sync
- 📄 Generate initial llms.txt from current documentation
- **Generator Script**: `scripts/generate-llms-txt.ts` parses all markdown docs in `content/docs/`
- **Automatic Updates**: CI/CD pipeline regenerates on any docs changes
- **Build Integration**: Added to `openagents.com` build process
- **Validation**: GitHub Actions validates format compliance
- Generated initial llms.txt successfully
- Verified route serves the …
=> feat: Add llms.txt support with automated generation

apps/openagents.com/src/routes/chat.ts, packages/psionic/src/markdown/service.ts
This PR adds proper markdown rendering and syntax highlighting to chat messages, enhancing readability and user experience.
Fixes #1055
- Exported the renderMarkdown function from Psionic's markdown service
- This allows direct usage of the existing Shiki-based rendering in other parts of the app
- Converted renderMessage function to async to support markdown rendering
- Updated message rendering to use await Promise.all() for concurrent processing
- Integrated markdown rendering into the message display pipeline
Added comprehensive markdown styling support:
- **Code blocks**: Proper styling for WebTUI pre elements with Shiki highlighting
- **Inline code**: Background styling with proper padding
- **Headings**: Styled h1-h6 with appropriate sizes and spacing
- **Lists**: Proper …
=> feat: Add markdown rendering and syntax highlighting to chat messages

apps/openagents.com/public/js/openagents-sdk-browser.js, apps/openagents.com/src/index.ts, apps/openagents.com/src/lib/chat-utils.ts, apps/openagents.com/src/routes/api/channels.ts, apps/openagents.com/src/routes/api/cloudflare.ts, apps/openagents.com/src/routes/api/config.ts, apps/openagents.com/src/routes/api/conversations.ts, apps/openagents.com/src/routes/api/markdown.ts, apps/openagents.com/src/routes/api/ollama.ts, apps/openagents.com/src/routes/api/openrouter.ts, apps/openagents.com/src/routes/api/test.ts, apps/openagents.com/src/routes/chat.ts, apps/openagents.com/src/routes/docs.ts, apps/openagents.com/src/routes/home.ts, docs/logs/20250623/1100-effecthttp-log.md, docs/logs/20250623/1105-effecthttp-reflections.md, docs/logs/20250623/1145-toresponse-error.md, docs/logs/20250623/1200-effecthttp-final-summary.md, docs/logs/20250623/1205-effect-detection-fix.md, docs/logs/20250623/1236-issue-resolved.md, packages/ai/src/providers/cloudflare/CloudflareClient.ts, packages/ai/src/providers/cloudflare/CloudflareLanguageModel.ts, packages/psionic/package.json, packages/psionic/src/adapters/elysia-adapter.ts, packages/psionic/src/core/app.ts, packages/psionic/src/index.ts, packages/psionic/src/types/index.ts
This PR implements proper Effect-based streaming for the Cloudflare AI provider and refactors the entire Psionic framework to be fully Effect-based, resolving multiple critical issues.
- **Issue**: Routes were failing with "Service not found: @effect/platform/HttpClient" 
- **Root Cause**: Using `Effect.runPromise` created isolated execution contexts without server-provided layers
- **Solution**: Refactored Psionic to support Effect-based route handlers that execute within the server context
- **Issue**: Streaming responses were not reaching the client
- **Root Cause**: Streaming logic was disconnected from HTTP response context
- **Solution**: Properly integrated Effect streams with HTTP responses using `Stream.toReadableStreamEffect()`
- **Issue**: Framework was mixing Effect and …
=> fix: Implement proper Effect-based streaming for Cloudflare AI provider

apps/desktop/package.json, apps/desktop/src/hooks/useSessionManager.ts, apps/desktop/src/panes/ChatPane.tsx
1. **Cmd/Ctrl+1 hotkey doesn't work** - `newProjectPath` was never initialized with a default value
2. **Desktop sessions not visible in mobile** - Sessions were only created locally, not in Convex
1. **Hardcoded default path** - Set `newProjectPath` to `/Users/christopherdavid/code/openagents` in `useSessionManager` hook
2. **Create Convex sessions** - Added `createClaudeSession` mutation call when creating desktop sessions
- Initialize `newProjectPath` with hardcoded default
- Import Convex mutation and API
- Call `createClaudeSession` after successful local session creation
- Desktop sessions now visible to mobile app queries
- Cmd/Ctrl+1 hotkey works immediately without manual path entry
- Both desktop and mobile can see all sessions regardless of where they were created
- Messages …
=> Fix: Initialize newProjectPath to enable Cmd+1 hotkey
