agentgraph/components/Node/Node.styles.ts
agentgraph/components/Node/Node.tsx
agentgraph/components/Node/TitleBar.tsx
agentgraph/components/UI/Label.tsx
agentgraph/components/UI/StyledUI.ts
agentgraph/components/ValueInput/ValueInput.tsx

Add basic node inputs

---

agentgraph/components/Canvas/Canvas.stories.tsx
agentgraph/components/Node/Node.demodata.ts
agentgraph/components/Node/Node.props.ts
agentgraph/components/Node/Node.stories.ts
agentgraph/components/Node/Node.tsx
resources/js/Pages/AgentNodes.tsx
resources/js/types/agents.d.ts

Add Agent node & story

---

agentgraph/components/Node/Node.demodata.ts
agentgraph/components/Node/Node.styles.ts
agentgraph/components/Node/Node.tsx
agentgraph/components/Node/TitleBar.tsx
agentgraph/components/Wallet/BitcoinBalance/BitcoinBalance.stories.ts
agentgraph/components/Wallet/BitcoinBalance/BitcoinBalance.styles.ts
agentgraph/components/Wallet/BitcoinBalance/BitcoinBalance.tsx
agentgraph/components/Wallet/BitcoinBalance/index.ts
agentgraph/components/Wallet/index.ts
resources/js/types/agents.d.ts

Add BitcoinBalance component to Agent node

---

agentgraph/components/Node/Node.demodata.ts
agentgraph/components/Node/Node.tsx
agentgraph/components/Node/TitleBar.tsx
agentgraph/components/Wallet/BitcoinBalance/BitcoinBalance.stories.ts
agentgraph/components/Wallet/BitcoinBalance/BitcoinBalance.tsx
database/factories/AgentFactory.php
database/migrations/2024_01_04_163056_add_balance_column_to_agents_table.php
resources/js/types/agents.d.ts
tests/Feature/PaymentTest.php
tests/Unit/AgentTest.php

Agent can have bitcoin balance

---

.storybook/preview.ts
resources/js/Components/builder/AgentBuilder/AgentBuilder.stories.tsx
resources/js/Components/builder/SimpleBuilder/SimpleBuilder.stories.tsx
resources/js/Components/builder/SimpleBuilder/SimpleBuilder.tsx
resources/js/Components/builder/SimpleBuilder/index.ts
resources/js/Components/nav/Navbar/Navbar.tsx
resources/js/Components/three/KamdoStage.tsx
resources/js/Pages/Builder.tsx
resources/js/app.tsx

Simpler Agent builder

---

app/Http/Controllers/PluginController.php
resources/views/components/bitcoin-amount.blade.php
resources/views/components/header.blade.php
resources/views/plugin-call-output.blade.php
resources/views/plugin-show.blade.php
routes/web.php
tests/Feature/PluginCallTest.php
tests/Feature/PluginViewTest.php

Plugin tester works with count_vowels

---

app/Http/Controllers/AgentController.php
app/Http/Controllers/StreamController.php
app/Models/Agent.php
app/Models/Step.php
app/View/Components/TaskRunner.php
resources/js/app.js
resources/views/agent-view.blade.php
resources/views/components/task-runner.blade.php
routes/web.php
tests/Unit/StepTest.php

Basic run task UI

---

app/Http/Controllers/NostrController.php
package-lock.json
package.json
resources/js/nostr/consts.js
resources/js/nostr/index.js
resources/js/nostr/nostr.js
resources/js/nostr/utils.js
resources/views/nostr-plugin-create.blade.php
resources/views/nostr-plugin.blade.php
resources/views/nostr-plugins.blade.php
resources/views/nostr-settings.blade.php
routes/web.php

Implement nostr client side for exploring and publish plugins for openagents on the nostr network using kind `30514`.
UI Example Video:
https://github.com/OpenAgentsInc/openagents/assets/148691676/75bb88ca-ed1f-4b5c-9869-356eaf7cfb3f
Example nostr event:
```json
{
"content": "https://example.com/plugin.wasm",
"tags": [
[
"d",
"example-plugin"
],
[
"title",
"Example Plugin"
],
[
"summary",
"This is a super useful and cool example plugin"
],
[
"published_at",
"1706630763862"
],
[
"price",
"0.001",
"btc"
]
],
"kind": 30514
}
```

implement nostr for exploring plugins

---

app/Models/Plugin.php
composer.json
composer.lock
routes/web.php
tests/Unit/PluginTest.php

Use LLM inference plugin 

---

resources/views/auth/login.blade.php
resources/views/components/chart.blade.php
resources/views/components/dropdown.blade.php
resources/views/components/input-label.blade.php
resources/views/components/stat-card.blade.php
resources/views/components/tab-link.blade.php
resources/views/earnings.blade.php
resources/views/layouts/app.blade.php
resources/views/layouts/guest.blade.php
resources/views/layouts/navigation.blade.php
routes/web.php
tailwind.config.js

Earnings dashboard mock

---

resources/views/auth/login.blade.php
resources/views/components/button.blade.php
resources/views/components/input-label.blade.php
resources/views/components/input.blade.php
resources/views/components/plugin-upload-form.blade.php
resources/views/components/textarea.blade.php

Tweak plugin UI

---

README.md
app/Http/Controllers/AgentController.php
database/seeders/ConnieSeeder.php
resources/views/agent-builder.blade copy.php
resources/views/agent-builder.blade.php
resources/views/agent-create.blade.php
resources/views/agent-list.blade.php
resources/views/auth/login.blade.php
resources/views/components/header.blade.php
resources/views/components/plugin.blade.php
tests/Feature/AgentListTest.php

Mock agent builder UI

---

app/Http/Controllers/PluginController.php
app/View/Components/Header.php
docker/8.3/php.ini
docs/README_for_agents.md
resources/views/agent-builder.blade.php
resources/views/layouts/app.blade.php
resources/views/plugin-show.blade.php

Run individual plugins from node graph

---

app/Livewire/Chat.php
resources/views/components/layouts/chat.blade.php
resources/views/livewire/chat.blade.php
routes/web.php
tests/Feature/Livewire/ChatTest.php

Connect chat to Livewire

---

app/Livewire/Chat.php
app/Models/Agent.php
resources/views/livewire/chat.blade.php

Show active plugin via Livewire stream

---

app/Livewire/Chat.php
app/Models/Agent.php
app/Models/StepExecuted.php
composer.json
composer.lock
resources/views/livewire/chat.blade.php

Stream LLM response

---

app/Livewire/Chat.php
app/Models/Agent.php
app/Models/StepExecuted.php
phpunit.xml
resources/views/components/layouts/chat.blade.php
resources/views/livewire/navbar.blade.php
resources/views/livewire/splash.blade.php
routes/web.php
tests/Feature/Livewire/ChatTest.php
tests/Feature/Livewire/NavbarTest.php

Livewire multichat

---

app/Http/Controllers/StaticController.php
resources/views/hud.blade.php
routes/web.php

Initial HUD scratchpad

---

app/Http/Controllers/Auth/NostrAuthController.php
app/Models/User.php
composer.lock
resources/views/livewire/login.blade.php
routes/auth.php
routes/web.php

Clean up Nostr auth

---

docs/introduction.md
resources/css/app.css
resources/views/docs/show.blade.php

Initial intro doc

---

app/Http/Controllers/StaticController.php
app/Livewire/Graph.php
app/Services/MarkdownParser.php
config/sheets.php
docs/agentgraph.md
resources/views/docs/agentgraph.blade.php
resources/views/livewire/graph.blade.php
resources/views/livewire/node.blade.php
routes/web.php

And add wire:navigate to the Markdown links

Add inline Livewire components to Markdown docs

---

app/Livewire/Chat.php
app/Services/Inferencer.php
resources/views/livewire/chat.blade.php

Add multimodal image input

---

app/AI/GroqAIGateway.php
app/Livewire/Chat.php
app/Services/Inferencer.php

https://twitter.com/OpenAgentsInc/status/1763037602767110155

Add Groq support

---

app/AI/FunctionCaller.php
app/AI/Inferencer.php
app/AI/MistralAIGateway.php
app/Models/Node.php
app/Models/Run.php
app/Services/Finnhub.php
composer.json
composer.lock

Temporarily only have access to ["AAPL", "TSLA", "WMT", "IBM", "GME", "BMW.DE", "SAP.DE", "BARC.L", "AC.PA", "MC.PA", "RY.TO", "AC.TO", "ARKK", "IVV", "LIT", "SPY"]

Extend agent to check stock price

---

app/AI/StabilityAIGateway.php
app/Models/Run.php
resources/views/components/chat/message.blade.php

Basic image gen via Stability

---

app/Console/Commands/CheckPrismTransaction.php
app/Console/Commands/CreatePrismUser.php
app/Console/Commands/SendPrismPayment.php
app/Http/Controllers/PrismController.php
app/Services/PrismService.php
package-lock.json
package.json
resources/js/app.js
resources/js/bootstrap.js
resources/views/layouts/guest.blade.php
resources/views/nwc.blade.php
routes/web.php

Works - sent 100 sats split into 50/50 between two Lightning addresses

Send initial prism

---

app/Livewire/PrismDashboard.php
app/View/Components/Pane.php
resources/css/app.css
resources/views/components/pane.blade.php
resources/views/livewire/prism-dashboard.blade.php
routes/web.php

Initial prism payment UI

---

app/Services/CodeAnalyzer.php
app/Services/GitHub.php
tests/Feature/AnalysisTest.php
tests/Feature/GitHubTest.php

Analyzing all markdown in the repo - good analysis

Initial Gemini Pro 1.5 analysis

---

app/AI/GeminiAIGateway.php
app/Console/Commands/UploadGeminiFile.php
app/Console/Commands/UploadGeminiFiles.php
resources/markdown/20240330-010948-gemini.md
resources/markdown/20240330-011035-gemini.md
resources/markdown/20240330-012002-gemini.md
resources/markdown/20240330-012348-gemini.md
resources/markdown/20240330-012826-gemini.md
resources/markdown/20240330-013155-gemini.md
tests/Feature/AnalysisTest.php
tests/Feature/GeminiTest.php

Multiple image & file-content analysis

---

app/Livewire/Auth/ChangePassword.php
app/Livewire/Auth/ForgetPassword.php
app/Livewire/Auth/Login.php
app/Livewire/Layouts/Sidebar/Content.php
app/Livewire/Modals/Chat/Delete.php
app/Livewire/Modals/Chat/Rename.php
resources/views/livewire/auth/change-password.blade.php
resources/views/livewire/auth/forget-password.blade.php
resources/views/livewire/auth/login.blade.php
resources/views/livewire/auth/register.blade.php
resources/views/livewire/modals/chat/delete.blade.php
resources/views/livewire/modals/chat/rename.blade.php
resources/views/livewire/sidebar-content.blade.php
resources/views/livewire/sidebar-thread.blade.php
routes/web.php

- [completed The password reset modal]
- [completed thread modals]

Auth thread

---

app/Livewire/Auth/ChangePassword.php
app/Livewire/Auth/ForgetPassword.php
app/Livewire/Layouts/Sidebar/Content.php
app/Livewire/Modals/Chat/Delete.php
app/Livewire/Modals/Chat/Rename.php
resources/css/app.css
resources/views/components/chat/message.blade.php
resources/views/components/chat/messagestreaming.blade.php

- OL/UL bullets & numbers
- Whitespace pre wrap on streaming msg

Markdown formatting fixes

---

app/Livewire/Chat.php
app/Livewire/Modals/Upgrade.php
resources/views/livewire/messages-remaining.blade.php
resources/views/livewire/modals/upgrade.blade.php

Upgrade modal

---

app/AI/HuggingfaceAIGateway.php
app/AI/Models.php
app/AI/SimpleInferencer.php
config/services.php

https://twitter.com/Spirit_Satoshi/status/1778785673631191218

Add Satoshi 7B

---

app/AI/SimpleInferencer.php
app/AI/TogetherAIGateway.php
tests/Browser/HappyPathTest.php
tests/Pest.php
tests/Unit/CohereAIGatewayTest.php
tests/Unit/HugginfaceAIGatewayTest.php
tests/Unit/PerplexityAIGatewayTest.php
tests/Unit/TogetherAIGatewayTest.php

* fix some typos in existing test messages
* fix the dusk test
* cleanup and add a test for TogetherAIGateway

Tests cleanup

---

app/Livewire/Settings.php
app/Models/User.php
database/migrations/2024_04_20_144458_add_lightning_address_to_users_table.php
resources/views/changelog.blade.php
resources/views/livewire/settings.blade.php

User can add Lightning Address

---

app/Livewire/Modals/ExploreAgents.php
app/Livewire/SidebarSwitcher.php
composer.lock
package-lock.json
package.json
resources/views/livewire/modals/explore-agents.blade.php
resources/views/livewire/model-dropdown.blade.php
resources/views/livewire/sidebar-content.blade.php
resources/views/livewire/sidebar-switcher.blade.php
resources/views/vendor/wire-elements-modal/modal.blade.php

fix modal issue

---

app/AI/Models.php
app/AI/NostrInference.php
app/AI/NostrRag.php
app/Events/NostrJobReady.php
app/Http/Controllers/Webhook/NostrHandlerController.php
app/Livewire/Auth/Join.php
app/Livewire/Chat.php
app/Livewire/Modals/ExploreAgents.php
app/Models/Message.php
app/Models/NostrJob.php
app/Services/NostrService.php
app/Vendors/WireElements/Modal/ModalComponent.php
config/services.php

reformat code per laravel standard

fix: pint cleanups

---

app/Console/Commands/UpdatePrismStatuses.php
app/Livewire/Agents/Create.php
resources/views/livewire/agents/create.blade.php
routes/web.php
tests/Browser/HappyPathTest.php

And update HappyPath dusk test to use the new agent create form

After agent create, redirect to agent chat

---

app/Http/Controllers/NostrAuthController.php

It seems that secp256k1-nostr-php reimplements the same verification function of  nostr-php and  nostr-php seems like better maintained and is already in the project deps.

Verify events with nostr-php instead of secp256k1-nostr-php

---

app/Livewire/Chat.php
app/Services/FlushLogEntriesJob.php
app/Services/NostrService.php
app/Services/OpenObserveLogger.php
app/Traits/SelectedModelOrAgentTrait.php
resources/views/livewire/agents/create.blade.php

Submitting some of the fixes I made earlier so it can be tested further.

fix a few rag/nostr issues

---

app/Livewire/Chat.php
resources/views/livewire/agents/create.blade.php

And fix selecting of agents from store

Re-enable code analysis on create

---

app/Livewire/Chat.php
app/Services/NostrService.php
routes/web.php

* in non-rag flow, use 'Llama 3 70B' for pro users
* for non-pro, and in rag flow, use 'Llama 3 8B'

use Together Llama models for agents

---

app/AI/Models.php
app/Http/Controllers/NostrAuthController.php
app/Traits/SelectedModelOrAgentTrait.php

Also declare some method return types and simplify some if/elses

make sure nostr event is an object before using

---

resources/views/livewire/chat.blade.php

Sometimes with get zero tokens, and now user messages may have input token count as well

tweak model name logic

---

app/AI/NostrRag.php
app/AI/SimpleInferencer.php
app/Livewire/Chat.php
package-lock.json

Also fix the name in package lock, other cleanups

use gpt-3.5-turbo-16k for internal rag calls, do not set max tokens

---

app/Console/Commands/PayAgentCreators.php

Set up payouts script

---

app/AI/NostrRag.php
app/AI/SimpleInferencer.php
app/Http/Controllers/Webhook/NostrHandlerController.php
app/Jobs/ProcessAgentRagStatus.php
app/Jobs/ProcessNostrRagReady.php
tests/Unit/NostrRagTest.php

added unit tests for message truncation from Nostr context, but it applies to both

make sure message history is in proper order

---

composer.json
composer.lock

use our own fork of php-nostr until this gets merged: https://github.com/swentel/nostr-php/pull/52

upgrade to php 8.3

---

app/AI/NostrInference.php
app/AI/SimpleInferencer.php
app/Livewire/Chat.php
app/Models/NostrJob.php
app/Services/ImageService.php
database/factories/NostrJobFactory.php
tests/Feature/CountLLMTokensTest.php
tests/Pest.php
tests/Unit/NostrInferenceTest.php
tests/Unit/SimpleInferencerTest.php

Also refactor inferencers some more

add detailed test for NostrInferencer

---

phpunit.xml
tests/Feature/Livewire/AgentCardStaticTest.php
tests/Feature/Livewire/AgentCardTest.php
tests/Feature/Livewire/BlogTest.php
tests/Feature/Livewire/ChangelogTest.php
tests/Feature/Livewire/ChatTest.php
tests/Feature/Livewire/LogsTest.php
tests/Feature/Livewire/ProWelcomeTest.php
tests/Feature/Livewire/StoreTest.php

also ignore app/Grpc for code coverage because that is auto-generated code

add more livewire tests with real assertions

---

app/Livewire/Agents/Edit.php
resources/views/livewire/agent-card-static.blade.php
resources/views/livewire/agent-card.blade.php
resources/views/livewire/agents/edit.blade.php
resources/views/livewire/changelog.blade.php

User can edit agent sats per message

---

app/Livewire/Chat.php
app/Livewire/Settings.php
app/Models/User.php
database/migrations/2024_05_30_225726_add_system_prompt_to_users_table.php
resources/views/livewire/settings.blade.php

To be used instead of "You are a helpful assistant." when provided.

add custom system prompt in user settings

---

app/Livewire/Agents/Create.php
app/Livewire/Agents/Edit.php
app/Livewire/Chat.php
app/Models/Agent.php
app/Traits/SelectedModelOrAgentTrait.php
database/migrations/2024_05_30_234145_add_model_to_agents_table.php
resources/css/app.css
resources/views/livewire/agents/create.blade.php
resources/views/livewire/agents/edit.blade.php

If pro model is selected, it will be used when a pro user uses the agent. Otherwise the regular model is used.

add model selectors to agents (regular and pro)

---

app/Http/Controllers/DashboardController.php
resources/css/inertia.css
resources/js/Layout.tsx
resources/js/Pages/Dashboard.tsx
resources/js/inertia.jsx
routes/web.php

Start new dashboard

---

app/View/Components/Dropdown.php
docs/for_agents/test_results.md
resources/views/components/sidebar-demo.blade.php
resources/views/components/sidebar.blade.php

Mock sidebar

---

app/Http/Controllers/ContentController.php
composer.json
composer.lock
package-lock.json
package.json
resources/js/Pages/Content/Show.tsx
resources/markdown/thesis.md
routes/web.php
tailwind.config.js

Add Markdown page and initial thesis post

---

app/AI/BedrockAIGateway.php
app/AI/BedrockMessageConverter.php
app/AI/Traits/BedrockMessageFormatting.php
app/Traits/UsesChat.php
app/Traits/UsesStreaming.php
docs/bedrock-tool-response-handling.md
docs/converse.md
docs/log.md
docs/test_results.md
docs/tool-example.md
docs/use-chat-flow.md
docs/use-chat-refactor.md
tests/Feature/UseChatToolsTest.php
tests/Unit/BedrockMessageConverterTest.php
tests/Unit/BedrockMessageEmptyContentTest.php
tests/Unit/BedrockMessageFormattingTest.php
tests/Unit/BedrockMessageNotBlankTest.php

Connect tools to chat

---

app/Http/Controllers/ChatController.php
resources/js/Components/nav-chats.tsx
resources/js/Layouts/MainLayout.tsx
resources/js/components/chat/ChatList.tsx
resources/js/components/chat/ToolInvocation.tsx
resources/js/components/nav-chats.tsx
resources/js/components/nav/Header.tsx
resources/js/components/nav/MainSidebar.tsx
tests/Feature/ChatThreadsTest.php

Load user chats, show team switcher

---

app/Http/Controllers/ProjectController.php
app/Http/Middleware/HandleInertiaRequests.php
app/Models/Project.php
app/Models/Thread.php
app/Models/User.php
app/Policies/ProjectPolicy.php
app/Providers/AuthServiceProvider.php
database/factories/ProjectFactory.php
database/migrations/2024_11_02_000000_add_project_features.php
docs/projects.md
docs/test_results.md
resources/js/Components/nav-projects.tsx
resources/js/Pages/Projects/Create.tsx
resources/js/Pages/Projects/Show.tsx
resources/js/components/nav-projects.tsx
resources/js/components/nav/MainSidebar.tsx
routes/web.php
tests/Unit/ProjectTest.php
tests/Unit/ThreadTest.php

Add initial project create/view

---

.gitignore
Cargo.lock
Cargo.toml
src/event.rs
src/main.rs
src/relay.rs
src/subscription.rs

This PR implements core NIP-01 relay functionality including:
- Event validation and verification
- Subscription handling with filters
- WebSocket server with proper message handling
- Event broadcasting to subscribers
- Tag indexing and filtering
Key components:
1. Event Module (`src/event.rs`)
- Event structure and validation
- Signature verification using secp256k1
- Tag indexing for efficient filtering
- Canonical event serialization
2. Subscription Module (`src/subscription.rs`) 
- Filter implementation
- Event matching logic
- Support for all NIP-01 filter types
3. Relay Module (`src/relay.rs`)
- WebSocket connection management
- Client message handling
- Event broadcasting
- Connection health monitoring
4. Updated Main (`src/main.rs`)
- WebSocket server setup
- Event broadcast …

Implement NIP-01: Basic Nostr Relay Functionality

---

Cargo.toml
migrations/20250110000000_initial.sql
src/db.rs
src/relay.rs

This PR adds PostgreSQL database integration to our Nostr relay implementation, following the requirements in #520.
- Added PostgreSQL database configuration to DigitalOcean deployment
- Set up managed database instance (nostr-db)
- Configured DATABASE_URL environment variable
- Created initial migration schema
- Implemented database layer with connection pooling
- Added CRUD operations for events
- Implemented efficient filtering and querying
1. `spec.yaml`: Added database configuration
2. `migrations/20250110000000_initial.sql`: Initial schema
3. `src/db.rs`: Database layer implementation
4. `src/db_test.rs`: Database tests
5. `src/main.rs`: Database initialization
6. `src/relay.rs`: Event persistence integration
7. `Cargo.toml`: Added SQLx dependencies
- Added comprehensive database …

Add PostgreSQL Database Integration

---

Cargo.lock
Cargo.toml
Dockerfile
configuration/base.yaml
configuration/local.yaml
configuration/production.yaml
src/configuration.rs
src/db.rs
src/main.rs

This PR adds a configuration-based approach to database connection handling, similar to the `oa` repository. Changes include:
1. Added YAML configuration files for different environments
2. Created a configuration module to handle settings
3. Updated the Database struct to support PgConnectOptions
4. Modified the Dockerfile to include configuration files
5. Removed direct DATABASE_URL environment variable dependency
This change makes the database configuration more robust and consistent with the `oa` repository's approach.

Add configuration-based database connection

---

src/configuration.rs

This PR adds support for DigitalOcean App Platform's database connection variables. The changes:
1. Added priority-based database connection configuration:
- First tries `DATABASE_URL` from environment (App Platform's primary method)
- Then tries individual `PG*` variables (App Platform's alternative method)
- Falls back to configuration file settings
2. Added logging to track which connection method is being used
3. Forces SSL mode to Required when using App Platform database variables
To use this:
1. Create your database in DigitalOcean
2. In App Platform, go to your app's Settings
3. Link the database to your app
4. The connection variables will be automatically injected
The app will now automatically detect and use the App Platform database connection details when available.

Add App Platform database support

---

Cargo.lock
Cargo.toml
src/database.rs
src/lib.rs
src/server/admin/middleware.rs
src/server/admin/routes.rs
src/server/config.rs
templates/admin/dashboard.html
templates/admin/login.html

Implements admin panel enhancements from #530:
- Added flexible auth methods supporting:
- Bearer token in Authorization header
- URL query parameter token
- Session cookie for browser access
- Added proper environment-aware auth bypass for local development
- Implemented login page and session management
- Created admin dashboard template with:
- System statistics display
- Real-time updates via HTMX
- Demo event creation
- Added responsive styling and background effects
- Integrated with existing design patterns
- Added comprehensive test coverage for:
- All authentication methods
- Admin routes and middleware
- Stats collection and display
- Demo event creation
- Fixed database connection handling in tests
- Improved test reliability and cleanup
Fixes #530

Enhance admin panel with UI and flexible authentication

---

docs/hierarchy.md
tests/agent/manager.rs
tests/agent/nostr.rs

This PR implements comprehensive tests for the agent manager service, following the implementation plan from #536.
Added test coverage for:
1. Core Agent Types
- Agent creation and validation
- Instance lifecycle management
- Plan and task management
- Task state transitions
- Configuration validation
2. Resource Management
- Memory and CPU limits
- Instance count limits
- Resource usage tracking
3. State Management
- State persistence
- Concurrent state updates
- State validation
- Error recovery
4. Event Integration
- Status events
- Task events
- Control events
- Error events
- Metric events
- Event validation
The MockAgentManager implementation includes:
- Instance state tracking using HashMap
- Instance count tracking for resource limits
- State persistence and retrieval
- Error …

Add agent manager tests and mock implementation

---

static/agents.html
static/changelog.html
static/index.html
static/templates/header.mustache
static/templates/textinput.mustache
static/video-series.html

---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/OpenAgentsInc/openagents/pull/545?shareId=f4219e33-b2d1-4742-b3ef-7e2464e3ebc0).

Standardize HTMX/Mustache front end components with Tailwind

---

src/main.rs

This PR updates the server configuration to read port and host settings from environment variables, similar to the main branch. This allows for better deployment flexibility, especially for Digital Ocean deployments.
Changes:
- Added environment variable support for PORT and HOST
- Added logging initialization and dotenv support
- Default port remains 8000 if not specified
- Default host is 0.0.0.0 if not specified
- Added better logging for server startup

Add port configuration from environment variables

---

Dockerfile
templates/pages/coming-soon.html

This PR fixes the missing assets (CSS, fonts, etc.) in the Docker container.
Changes:
- Added `COPY --from=builder /app/assets assets` to copy the assets directory into the runtime container
- Assets directory includes:
- main.css
- fonts.css
- fonts directory
- favicon.ico
This ensures that all static assets are available when the container runs, fixing the missing CSS and other asset issues in production.

Fix missing assets in Docker container

---

templates/header.html
templates/layouts/base.html
templates/macros/nav.html

This PR improves mobile responsiveness across the site:
1. Added proper viewport meta tag and mobile-first responsive design
2. Improved mobile navigation with better touch targets
3. Optimized layout spacing and text sizes for mobile
4. Added overflow-x-hidden to prevent horizontal scroll
5. Adjusted grid layout for better mobile presentation
6. Added touch-manipulation for better touch interaction
7. Made nav dots and spacing responsive
Changes:
- Added viewport meta tag and mobile optimization in base.html
- Updated header grid layout for mobile-first design
- Optimized nav buttons for mobile touch targets and text size
- Added responsive spacing and sizing throughout

Mobile Responsive Optimization

---

src/server/services/solver/ws.rs

This PR fixes the issue where the solver would fail when DeepSeek returns a response without reasoning content.
Changes made:
1. Modified pattern matching to handle `Ok((files_list, files_reasoning))` instead of requiring `Some(files_reasoning)`
2. Added `unwrap_or_else` with default "No reasoning provided" message for cases where reasoning is None
3. Updated logging to only log reasoning when it's available
4. Added proper handling for both files and solution reasoning being optional
This fixes the compiler errors:
```rust
error[E0004]: non-exhaustive patterns: `Ok((_, None))` not covered
--> src/server/services/solver/ws.rs:97:23
```
Testing:
- Compiles successfully
- Handles cases where DeepSeek returns no reasoning
- Maintains existing functionality when reasoning is provided
- …

Fix DeepSeek None reasoning handling

---

assets/main.css
docs/repomap.md
styles/tailwind.css
templates/components/chat/head_scripts.html
templates/components/chat/websocket_scripts.html

Closes #599
Adds markdown support with:
- Syntax highlighting for code blocks
- Copy code button in code blocks
- Proper code block formatting
- Fixed copy button positioning inside code blocks
The copy button appears in the top-right corner of each code block and provides visual feedback when clicked.

Add markdown support with syntax highlighting and copy code button

---

src/solver/context.rs

This PR integrates the solution generation functionality into SolutionContext.
Changes:
1. Added new methods to SolutionContext:
- `generate_changes` - Generate changes for a specific file
- `parse_changes` - Parse SEARCH/REPLACE blocks into changes
- Updated `generate_file_list` to use new functionality
2. Added comprehensive tests:
- File list generation
- Change generation
- SEARCH/REPLACE parsing
- Full solution flow
3. Improved error handling and validation throughout
This provides a complete solution generation workflow:
1. Generate list of files to modify
2. Generate changes for each file
3. Parse and validate changes
4. Apply changes with proper error handling
Part of #625

Solution Generation v2: Context Integration

---

src/bin/solver.rs

This PR updates the solver binary to use the new solution generation functionality.
Changes:
1. Added solution generation flow:
- Generate list of files to modify with reasoning
- Generate and apply changes for each file
- Display progress and reasoning at each step
2. Improved output:
- Added colored progress indicators
- Show reasoning for file selection and changes
- Better progress reporting
3. Enhanced PR creation:
- Include list of modified files
- Include implementation plan
- Better PR description format
The solver binary now provides a complete workflow:
1. Analyze issue and generate implementation plan
2. Identify files that need changes
3. Generate and apply changes for each file
4. Create PR with detailed description
Part of #625

Solution Generation v2: Binary Update

---

README.md

Automated solution for issue #634
Implementation Plan:
Focused Implementation Plan for Issue #634: Update README
Files to Modify:
1. README.md
Specific Changes in README.md:
- Locate the section after the project introduction
- Add a new section titled "## Solver Functionality"
- Insert the following content verbatim:
```markdown
The solver is an intelligent automation tool designed to help developers streamline code changes and problem-solving across repositories.
- Automated GitHub issue analysis
- Context-aware code change generation
- Intelligent branch and pull request creation
- Comprehensive repository mapping
```bash
./solver --issue https://github.com/org/repo/issues/123
```
- GitHub authentication token
- Rust toolchain (1.70+ recommended)
- Git installed
```
Implementation …

Implement solution for #634

---

src/bin/solver_impl/planning.rs

Removes unused constants and functions from planning.rs to address dead code warnings:
- Removed unused error message constants
- Removed unused utility functions
- Removed unused test for validate_changes_relevance
- Kept only the functions and constants that are used in tests or exported
This change helps reduce code maintenance burden and improves code clarity by removing dead code.

refactor: remove unused constants and functions

---

Cargo.toml
src/bin/analyze-issue.rs
src/server/hyperview/handlers/issue_analysis.rs
src/server/hyperview/handlers/mod.rs
src/server/hyperview/handlers/repos.rs
src/server/hyperview/routes.rs
src/server/services/github_issue/analyzer.rs
src/server/services/github_issue/mod.rs
src/server/services/openrouter/mod.rs
src/server/services/openrouter/service.rs
src/server/services/openrouter/types.rs
tests/auth_error_handling.rs

This PR implements OpenRouter structured output integration for GitHub issue analysis, as detailed in #695.
- Added structured output types and request handling to OpenRouter service
- Created new issue analysis service
- Added Hyperview UI integration for issue analysis
- Added new routes and handlers for issue analysis flow
- Implemented JSON schema validation for consistent responses
- Tested with hardcoded issue #579
- Verified structured output formatting
- Tested UI flow and navigation
- Verified error handling
1. Repository list shows "View Issues" button
2. Issues list shows "Analyze Issue" button
3. Analysis view shows formatted structured output
4. Navigation between views works as expected
- Currently using hardcoded issue #579 for testing
- Future work will make issue …

Implement OpenRouter Structured Output for GitHub Issue Analysis

---

pnpm-lock.yaml
src/main.rs
src/server/hyperview/ws.rs
src/server/ws/transport.rs
src/server/ws/types.rs
templates/pages/main.xml

Stream demo

---

docs/repomap.md
frontend/app/+types/root.ts
frontend/app/components/chat-input.tsx
frontend/app/components/header-bar.tsx
frontend/app/components/repo-selector.tsx
frontend/app/components/ui/dropdown-menu.tsx
frontend/app/components/ui/popover.tsx
frontend/app/root.tsx
frontend/app/routes/_layout.tsx
frontend/app/routes/chat/$id.tsx
frontend/app/routes/chat/_layout.tsx
frontend/app/routes/chat/index.tsx
frontend/app/routes/login-full.tsx
frontend/app/routes/login.tsx
frontend/app/styles/globals.css
frontend/package.json
frontend/pnpm-lock.yaml

https://x.com/OpenAgentsInc/status/1892293678854545668

Add initial repo chat UI

---

backend/src/server/ws/handlers/chat.rs
frontend/app/lib/agentsync/hooks/useAgentSync.ts
frontend/app/routes/chat/$id.tsx
frontend/app/routes/chat/index.tsx

This PR refactors our chat sync implementation to use WebSockets instead of manual SSE parsing. The changes:
1. Added WebSocket handler in backend:
- Unified message handling for both first and follow-up messages
- Proper streaming support with content and reasoning
- Better error handling and connection management
2. Created WebSocket client wrapper:
- Automatic reconnection with exponential backoff
- Message type safety with TypeScript
- Proper cleanup on unmount
3. Updated useAgentSync hook:
- Removed manual SSE parsing
- Added WebSocket-based streaming
- Better state management
- Proper error handling
4. Modified chat routes:
- Immediate navigation on first message
- Proper loading states
- Better error handling
- Disabled input during streaming
Key benefits:
- Simpler, more …

Refactor chat sync to use WebSocket-based streaming

---

docs/onyx-wallet.md

This PR adds comprehensive documentation for the Onyx wallet integration, including:
- Current implementation overview
- Technical stack details using Breez SDK
- Planned additional screens and features
- Integration plans with the agent system
- Security considerations
- Future enhancement roadmap
- Implementation timeline
The document serves as both documentation and a planning resource for expanding the wallet functionality in the Onyx mobile app.

Add Onyx wallet documentation

---

.gitignore
apps/coder/tsconfig.json
docs/cross-platform-ui-components.md
docs/shared-ui-components.md
package.json
packages/ui/src/components/Button/Button.tsx

Fixes #771
This PR implements the direct source import approach from the tryit branch, eliminating the need for a separate build step for the UI package.
Key changes:
1. Updated UI package configuration:
- Simplified tsconfig.json to support direct source imports
- Removed build scripts and dist configuration
- Updated module resolution settings
2. Updated Coder app configuration:
- Added UI package source files to compilation scope
- Set proper rootDir for monorepo structure
- Updated path mappings to point directly to source
3. Removed build-related configurations:
- Removed tsup and build scripts
- Removed dist directory references
- Updated package.json to use source files directly
This approach follows the pattern documented in docs/cross-platform-ui-components.md, allowing both apps …

Fix TypeScript configuration for direct source imports

---

apps/chatserver/package.json
apps/chatserver/src/index.ts
apps/onyx/app.json
apps/onyx/app/models/chat/ChatStorage.native.ts
apps/onyx/app/screens/ChatScreen/ChatScreen.styles.ts
apps/onyx/app/screens/ChatScreen/ChatScreen.tsx
apps/onyx/app/screens/WalletScreen/AgentEarningsScreen.tsx
apps/onyx/app/screens/WalletScreen/BalanceHeader.tsx
apps/onyx/app/utils/generateAPIUrl.ts
apps/onyx/app/utils/polyfills.ts
apps/onyx/package.json
apps/onyx/tsconfig.json
packages/ui/src/components/Card/Card.styles.ts
packages/ui/src/components/Card/Card.tsx
packages/ui/src/components/Card/Card.types.ts
packages/ui/src/components/Card/index.ts
packages/ui/src/index.ts
yarn.lock

[Onyx] Connect chat via AI SDK 

---

apps/coder/src/server/server.ts
package.json

This PR implements and closes #815 by adding both local and remote MCP server support to the Coder app.
- Implemented local MCP server support within Electron app
- Maintained remote MCP server compatibility
- Fixed streaming response handling through IPC
- Added comprehensive error handling and logging
- Improved type safety with explicit PlainResponseData type
1. **IPC Communication**:
- Redesigned data flow between main and renderer processes
- Implemented proper serialization of response data
- Enhanced error handling with detailed logging
2. **MCP Server Integration**:
- Added support for both local and remote MCP servers
- Implemented proper response streaming
- Ensured compatibility with existing chat persistence
3. **Testing**:
- Verified functionality with both local and remote …

Add local and remote MCP server support to Coder app

---

apps/coder/src/components/ui/chat-message.tsx
apps/coder/src/components/ui/chat.tsx
apps/coder/src/components/ui/code-block.tsx
apps/coder/src/components/ui/markdown-renderer.tsx
apps/coder/src/main.ts
apps/coder/src/pages/settings/MCPClientsPage.tsx
apps/coder/src/pages/settings/PreferencesPage.tsx
apps/coder/src/pages/settings/SettingsLayout.tsx
apps/coder/src/providers/ApiKeyProvider.tsx
apps/coder/src/providers/ChatStateProvider.tsx
apps/coder/src/routes/routes.tsx
apps/coder/src/server/mcp-api.ts
apps/coder/src/server/mcp-clients.ts
apps/coder/src/server/server.ts
docs/issues/839/final-summary.md
docs/issues/839/implementation.md
docs/issues/839/intro.md
docs/issues/839/summary.md
docs/issues/839/usage.md
docs/mcp-client-configuration.md
docs/mcp-tool-error-handling.md
packages/core/src/chat/usePersistentChat.ts
packages/core/src/db/database.ts
packages/core/src/db/repositories/settings-repository.ts
packages/core/src/db/schema.ts
packages/core/src/db/types.ts

This PR implements a comprehensive MCP client configuration system that allows users to manage Model Context Protocol clients through a settings interface.
1. **Data Model**:
- Added `MCPClientConfig` interface for client configurations
- Extended `Settings` interface to store MCP client configurations
- Added status tracking information
2. **MCP Clients Module**:
- Refactored to load configurations from settings
- Implemented dynamic initialization and reinitialization
- Added proper cleanup and status updates
3. **API Layer**:
- Created RESTful endpoints for client management
- Added validation and error handling
- Implemented refresh and reinitialize operations
4. **Settings UI**:
- Created dedicated settings page for MCP clients
- Added add/edit/delete functionality
- Implemented …

Add MCP Client Configuration System

---

apps/coder/forge.config.cjs
apps/coder/package.json
apps/coder/src/components/ui/code-block.tsx
apps/coder/src/helpers/ipc/theme/theme-context.ts
apps/coder/src/helpers/ipc/window/window-context.ts
apps/coder/src/main.ts
apps/coder/src/main/dbService.ts
apps/coder/src/server/server.ts
apps/coder/vite.main.config.ts
docs/issues/848/fs-extra-fix.md
docs/issues/848/implementation_log.md
docs/issues/848/node-fs-fix.md

This PR fixes issues #848 and #850 related to application initialization, packaging errors, and window loading failures in production builds.
**Changes:**
1.  **Removed `fs-extra` Dependency:** Replaced usage of `fs-extra` in `main/dbService.ts` with the native Node.js `fs` module to resolve the `Cannot find module 'fs-extra'` error in packaged builds. Externalizing or unpacking the module proved ineffective, suggesting removal was the simplest solution.
2.  **Fixed Preload Script Context Isolation Errors:** Corrected invalid `window.require('electron')` calls in preload context helper files (`helpers/ipc/window/window-context.ts` and `helpers/ipc/theme/theme-context.ts`). These calls violated context isolation rules, causing the preload script to fail and preventing contextBridge APIs …

Fix packaging error

---

apps/website/app/components/agent/solver-connector.tsx
apps/website/app/components/agent/solver-controls.tsx
apps/website/app/components/layout/headers/issues/header.tsx
apps/website/app/routes/issues/$id.tsx
packages/agents/docs/SOLVER-README.md
packages/agents/docs/solver-agent-fixes.md
packages/agents/src/agents/solver/index.ts
packages/agents/src/agents/solver/prompts.ts
packages/agents/src/agents/solver/types.ts
packages/agents/src/common/open-agent.ts

Improve UI, connect Solver chat with issue details

---

apps/wallet/docs/20250513/2122-invoice-fix.md
apps/wallet/docs/20250513/2122-invoice-log.md
apps/wallet/docs/20250513/2127-bolt11-instructions.md
apps/wallet/docs/20250513/2127-bolt11-log.md
apps/wallet/docs/20250513/2131-listener-instructions.md
apps/wallet/docs/20250513/2151-bolt11-followup-instructions.md
apps/wallet/package.json
apps/wallet/src/App.tsx
apps/wallet/src/components/TransactionItem.tsx
apps/wallet/src/lib/invoice-utils.ts
pnpm-lock.yaml

- Fix Lightning invoice send message
- Add confirmation on invoice send payment
- Don't show 'sender key tweak' message

Wallet fixes

---

CLAUDE.md
apps/openagents.com/app/chat/[id]/page.tsx
apps/openagents.com/app/page.tsx
apps/openagents.com/components/ChatSidebar.tsx
apps/openagents.com/convex/_generated/api.d.ts
apps/openagents.com/convex/conversations.ts
apps/openagents.com/convex/schema.ts
apps/openagents.com/hooks/useAuth.ts

This PR implements a complete conversation management system with Convex, enabling users to create, navigate, and persist chat conversations.
- Added  table to store chat sessions with user ownership
- Added  table to store individual messages within conversations
- Integrated with existing Convex auth system
- Created comprehensive Convex functions for conversation operations:
- : Get all conversations for authenticated user
- : Fetch single conversation with messages
- : Create new conversation
- : Add messages to conversations
- : Update conversation metadata
- : Delete conversations
- : Get conversations organized by time
- Updated ChatSidebar to display real conversations from database
- Created dynamic  pages for individual conversations
- Updated homepage to create new …

feat: Implement Full Conversation Management System

---

apps/desktop/src/components/hud/Hotbar.tsx
apps/desktop/src/components/hud/HotbarItem.tsx
apps/desktop/src/hooks/useKeyboardShortcuts.ts
apps/desktop/src/stores/hotbar.ts

This PR implements visual feedback for the hotkey system, addressing the issues outlined in #1172:
1. **Press Animation**: Added visual feedback when keyboard shortcuts are pressed
2. **Active State Reflection**: Hotbar items now show active state when corresponding panes are open  
3. **Smooth Animations**: Implemented smooth press state transitions with scale and shadow effects
- Created `hotbar.ts` store to track pressed hotbar slots globally
- **Hotbar.tsx**: 
- Connected pane visibility states from `usePaneStore`
- Pass `isActive` prop to panes (slots 3, 4, 7)
- Pass `isPressed` prop to all interactive slots
- **HotbarItem.tsx**:
- Added `isPressed` prop support
- Added pressed state styling with scale animation and inner shadow
- **useKeyboardShortcuts.ts**:
- Track keydown/keyup …

Enhance hotkey visual feedback: Show active states and press animations

---

apps/desktop/src/App.tsx
apps/desktop/src/hooks/useSessionManager.ts

Desktop-initiated sessions always stayed in "active" status and were never marked as "processed" like mobile-initiated sessions. This could cause issues with querying for truly active sessions and makes the session lifecycle inconsistent.
Added logic to mark desktop sessions as "processed" in two scenarios:
1. When a session is explicitly stopped via `stopSession()`
2. When the desktop app closes or reloads
- Added `updateSessionStatus` mutation to `useSessionManager` hook
- Call `updateSessionStatus` to mark sessions as "processed" when stopped
- Added cleanup effect in `App.tsx` to mark all active sessions as "processed" on unmount
- Added `beforeunload` event listener to handle browser close/reload
- Desktop sessions now follow the same lifecycle as mobile sessions
- Sessions …

Fix: Mark desktop sessions as processed when stopped or app closes
